name: Greetings

on: [ push, workflow_dispatch ]

jobs:
  greeting:
    strategy:
      matrix: 
        version: [1, 2, 3]
        operation-system: [ubuntu-latest, windows-latest]
        exclude: 
          - version: 2
            operation-system: windows-latest
    runs-on: ${{ matrix.operation-system }}
    steps:
      - name: Print Greeting
        run: |
          echo "Hello and welcome! 👋"
          echo "ram"
      - name: Print Greeting - 
        run: echo "Hello and welcome! -2 "
      - name: Get node
        uses: actions/checkout@v4
      - name:
        run: |
          echo "i am a good persson"
          echo "CHAPRI"
      - name: REsuable Deploy
        uses: ./.github/workflows/reuseable.yaml
  wishing:
    uses: ./.github/workflows/reuseable.yaml