name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - name: Print Greeting
        run: echo "Hello and welcome! 👋"
      - name: Print Greeting - 
        run: echo "Hello and welcome! -2 👋"