name: Greetings

on: workflow_dispatch

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - name: Print Greeting
        run: |
          echo "Hello and welcome! 👋"
          echo "ram"
      - name: Print Greeting - 
        run: echo "Hello and welcome! -2 "