name: Greetings

on: [ push, workflow_dispatch ]

jobs:
  greeting:
    strategy:
      matrix: 
        versin: [1, 2, 3]
        operation-system: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.operation-system }}
    steps:
      - name: Print Greeting
        run: |
          echo "Hello and welcome! 👋"
          echo "ram"
      - name: Print Greeting - 
        run: echo "Hello and welcome! -2 "
      - name: Get node
        uses: actions/checkout@v4
      - name:
        run: |
          echo "i am a good persson"
          echo "CHAPRI"
  wishing:
    runs-on: ubuntu-latest
    steps:
      - name: Print Greeting
        run: echo "Hello world"