name: Greetings

on: [ push, workflow_dispatch ]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - name: Print Greeting
        run: |
          echo "Hello and welcome! 👋"
          echo "ram"
      - name: Print Greeting 2
        run: echo "Hello and welcome! -2"
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Print message
        run: |
          echo "I am a good person"
          echo "CHAPRI"

  wishing:
    uses: ./.github/workflows/reuseable.yaml
    with:
      env_name: UAT
  
  wishing-2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4   # ✅ Checkout your repo first
      - uses: ./.github/actions/mesg
        with:
          who-to-greet: "hello users"
