name: Actions Metadata
on:
  pull_request:
    type:
      - opened
  branches:
    - main
    - 'dev-*'
  workflow_dispatch:
  push:
    branches:
      - main
      - 'dev-*'
jobs:
  Actions-info:
    runs-on: ubuntu-latest
    steps:
      - name: To featch the metadate content
        run: echo "${{ toJSON(github) }}"