name: out-put Greetings

on: [ push, workflow_dispatch ]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - name: Print Greeting
        run: |
          echo "H=here is out put 👋"
          echo "${{ toJson(github) }}"