name: Re-useable Deployment
on:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Output info
        run: echo "Deploying & uploading by reusable workflow by siva"
