name: Re-useable Deployment
on:
  workflow_call:
    inputs:
      env_name:
        type: string
        required: false
        description: "Here we have to type environment name"
        default: dev
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Output info
        run: | 
            echo "Deploying to environment: ${{ inputs.env_name }}"
  deploy-prod:
    runs-on: ubuntu-latest
    steps:
      - name: Output info
        run: | 
            echo "Deploying to environment prod: ${{ inputs.env_name }}"