name: Re-useable Deployment

on:
  workflow_call:
    inputs:
      env_name:
        type: string
        required: true
        description: "Here we have to type environment name"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Output info
        run: echo "Deploying to environment: ${{ inputs.env_name }}"
