name: Re-useable Deployment
on: workflow_call
jobs:
    deploy:
        runs-on: ununtu-latest
        steps:
          - name: output info
            run: echo "Deploying $ uoloading by reuseable wf"
