name: Re-useable Deployment

on:
  workflow_call:
    inputs:
      env_name:
        description: "Here we have to type environment name"
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Output info
        run: echo "Deploying to environment: ${{ inputs.env_name }}"
